### ISSUE TITLE
not support with unicode 

### ISSUE THREAD

**Issue by jackie-maxx** [arthas1888/flutter_pos_printer_platform#1]

**Comment by arthas1888** [comment]
Could you provide more info, please

**Comment by jackie-maxx** [comment]
when i try to print unicode 
bytes += generator.text("សួរស្តីកម្ពុជា" , styles: const PosStyles(align: PosAlign.center));
it error with this line

**Comment by jackie-maxx** [comment]
> this is not a error of this library, the generator library is https://pub.dev/packages/flutter_esc_pos_utils

How can i fix this ? can u demo to print unicode ?
