### ISSUE TITLE
Debug Error (Microsoft Visual C++ Runtime Library)

### ISSUE THREAD

**Issue by xaldarof** [arthas1888/flutter_pos_printer_platform#10]
![image](https://user-images.githubusercontent.com/69597351/190640398-5533c463-5e39-4a41-82af-8733fa3b00b6.png)

If printer is connected to my computer it works without errors, but when i send bytes to already disconnected printer it throws this error and i  cant to catch this error with try {} catch.

![image](https://user-images.githubusercontent.com/69597351/190640302-65a55d3b-d403-4e7f-b636-fbc1d7f42cff.png)

**Comment by arthas1888** [comment]
thanks, I included your code flutter_pos_printer_platform 1.0.6
