### ISSUE TITLE
usb label printer not work on windows

### ISSUE THREAD

**Issue by hamzakj** [arthas1888/flutter_pos_printer_platform#13]
i tried to print via usb label printer (XP-358BM)
but there is no response from printer when i try to print test ticket
and in queue list in printer settings ... there is message show fast after click print test ticket then disappear fast too
the message : 'FeedMe Pos Print Job ' with no any process from printer
knowing the print test page in printer properties is work

**Comment by arthas1888** [comment]
I think it is problem of your printer because is a usb label printer maybe you need to set it up first
try with some sdk of native platffom and if it works, tell me
I test with XP-A160H without any problem
