### ISSUE TITLE
TCP IP print not work on label printer on windows

### ISSUE THREAD

**Issue by hamzakj** [arthas1888/flutter_pos_printer_platform#14]
I tried too print with a LAN cable and I set up the printer IP in settings and printed a test page its work !!
then I tested a ping of printer IP ... its available !!
on  your app sample when I test print then in run there is a message displayed
"SocketException  : Connection timed out , host : 192.168.123.100 , port : 9100 "
and I tried another label printer with USB and same issue in #13 .

and did you mean I should try native SDK in C# ?

**Comment by arthas1888** [comment]
for now, I've not thought to support this kind of printers
