### ISSUE TITLE
Crashed - Microsoft visual c++ Runtime Library error dialog pops up

### ISSUE THREAD

**Issue by thangmam** [arthas1888/flutter_pos_printer_platform#2]
Hello, thanks for the awesome plugin. I was able to print it earlier without any issues, however when i ran my project again after a few hours. It crashes when i call the PrintManager.instance.send() method. 

On further investigation, the error seems to pop up from this line(87) in printer.cpp file **dwJob = StartDocPrinterW(_hPrinter, 1, (LPBYTE)&docInfo);**.
dwJob value is 0 which throws **std::exception("StartDocPrinterW error.")** error and then line below does not satisfy the condition **if (written != data.size())** at line no. 111 which throws the exception ** throw std::exception("Fail to send all bytes");** again.

Any help will be greatly appreciated. Thank you

**Comment by arthas1888** [comment]
I can't reproduce this issue, could you gime more details?

**Comment by xaldarof** [comment]
Hello i fixed it, in my case was error like this :

(Runtime C++ library) Debug error program abort() has been called.

To fix it go to: 
\flutter_pos_printer_platform\windows\include\printer.cpp

end there are method named printBytes(); [69 - 122]
delete that method and paste this code:


`BOOL PrintManager::printBytes(std::vector<uint8_t> data)
{
    BOOL status = false;
    BOOL success = true;
    DOC_INFO_1W docInfo;
    DWORD dwJob = 0;
    DWORD written = 0;

    if (_hPrinter == INVALID_HANDLE_VALUE)
    {
      //  throw std::exception("Printer handle is invalid.");
                  success =  false;

    }

    // Fill in default value of the print document
    docInfo.pDocName = L"FeedMe POS Print Job";
    docInfo.pOutputFile = NULL;
    docInfo.pDatatype = L"RAW";

    // Inform the spooler there is a new document
    dwJob = StartDocPrinterW(_hPrinter, 1, (LPBYTE)&docInfo);
    if (dwJob > 0)
    {
        // Start page
        status = StartPagePrinter(_hPrinter);
        if (status)
        {
            // Send data to the printer
            status = WritePrinter(_hPrinter, (LPVOID)std::data(data), (DWORD)data.size(), &written);
            EndPagePrinter(_hPrinter);
        }
        else
        {
        //    throw std::exception("StartPagePrinter error.");
                    success =  false;
        }
        // Inform the spooler that the document hsa ended
        EndDocPrinter(_hPrinter);
    }
    else
    {
       // throw std::exception("StartDocPrinterW error.");
                   success = false;
    }

    // Check if all data are flushed
    if (written != data.size())
    {
        //throw std::exception("Fail to send all bytes");
            success =  false;
    }

    return success;
}`

**Comment by arthas1888** [comment]
Solve flutter_pos_printer_platform 1.0.6
