### ISSUE TITLE
Can't scan devices already "CONNECTED" before open app on IOS

### ISSUE THREAD

**Issue by hidenxtt2001** [arthas1888/flutter_pos_printer_platform#21]
in my case, when i pair with a printer before open app then open app and scan but it didn't show in scanner
Please help me.

**Comment by ot-repo** [comment]
Hi, I have the same problem. After the first device is connected to the printer, no other device can find the printer or connect to it. Even disconnect does not help here. 

Any kind of help is highly appreciated!

Thank you.

**Comment by arthas1888** [comment]
update the lib
