### ISSUE TITLE
Is there any way to skip the printer connection part?

### ISSUE THREAD

**Issue by BrunoSantosCosta** [arthas1888/flutter_pos_printer_platform#22]
I would like to leave the printer connected to the app, and whenever the user opens the app, they don't need to make the connection again

**Comment by arthas1888** [comment]
@BrunoSantosCosta do you mean USB connection?

**Comment by BrunoSantosCosta** [comment]
exactly, I am currently using it for usb connection on an android device


but whenever the user enters, he needs to connect to the printer

**Comment by arthas1888** [comment]
in that case you just need to enable the native broadcast receiver
in AndroidManifest put:

<receiver
            android:name="com.sersoluciones.flutter_pos_printer_platform.usb.UsbReceiver"
            android:exported="false">

            <intent-filter>
                <action android:name="android.hardware.usb.action.ACTION_USB_PERMISSION" />
                <action android:name="android.hardware.usb.action.USB_DEVICE_ATTACHED" />
                
            </intent-filter>
        </receiver>

and that's all

**Comment by BrunoSantosCosta** [comment]
Thanks bro!
