### ISSUE TITLE
Tooltips display messages in Spanish.

### ISSUE THREAD

**Issue by ironda2020** [arthas1888/flutter_pos_printer_platform#26]
Hi,
is it possible to internationalize messages that show in tooltips? (for example : "No se puede establecer conexión Bluetooth" and "Se ha perdido conexión Bluetooth" )
if not put them at least in English please
Thanks in advance

**Comment by lamyae88** [comment]
Good evening, 
I am using this plugin and encountered the same problem. is there a way to internationalize these messages (i18n)?? 
THANK YOU

**Comment by arthas1888** [comment]
solved flutter_pos_printer_platform: ^1.1.0
It supports spanish and english locale, default english
