### ISSUE TITLE
Printing weird characters

### ISSUE THREAD

**Issue by shameemalim** [arthas1888/flutter_pos_printer_platform#28]
Bluetooth thermal printing works fine on some printers but on some its printing long weird characters especially when using images .Normal png images.

**Comment by arthas1888** [comment]
hi, you have to review this library https://pub.dev/packages/flutter_esc_pos_utils, that's not mine 
[flutter_pos_printer_platform](https://github.com/arthas1888/flutter_pos_printer_platform) is just the way to print bytes
