### ISSUE TITLE
Crash on Android 12

### ISSUE THREAD

**Issue by kamikhanz** [arthas1888/flutter_pos_printer_platform#3]
I have a crash on a tablet SM-T505 and android 12, I got this error:
```
kotlin.UninitializedPropertyAccessException: lateinit property bluetoothService has not been initialized
at com.sersoluciones.flutter_pos_printer_platform.FlutterPosPrinterPlatformPlugin.verifyIsBluetoothIsOn(FlutterPosPrinterPlatformPlugin.kt:264)
at com.sersoluciones.flutter_pos_printer_platform.FlutterPosPrinterPlatformPlugin.onMethodCall(FlutterPosPrinterPlatformPlugin.kt:168)
```
On same model tablet but with android 11 works without any issue.

**Comment by arthas1888** [comment]
Change the targetSdkVersion for Android

android/app/build.gradle:

In build.gradle set

   defaultConfig {
        ...
        minSdkVersion 21
        targetSdkVersion 30
        ...

**Comment by khairulTonu** [comment]
> Change the targetSdkVersion for Android
> 
> android/app/build.gradle:
> 
> In build.gradle set
> 
> defaultConfig { ... minSdkVersion 21 targetSdkVersion 30 ...

targetSdkVersion 30 is not supported in Google Play Store now. Minimum version is 31. Though this solution works, but you can't go to production with this.

**Comment by arthas1888** [comment]
the last release has the solution

**Comment by khairulTonu** [comment]
> the last release has the solution

@arthas1888 Already tried the latest release. But it's not working on Android 12 for USB Connection. It crashes while usb permission given through the popup.

**Comment by arthas1888** [comment]
Hi, in the last release this bug was solved
Support me https://www.paypal.com/donate/?hosted_button_id=92HK6VNCK7MUY
