### ISSUE TITLE
image 4.x dependency

### ISSUE THREAD

**Issue by jobypthomas** [arthas1888/flutter_pos_printer_platform#30]
Hi,
@arthas1888 @xaldarof 
I am trying to use this package but failing due to the incompatibility with image 4.x:
`Because flutter_pos_printer_platform >=1.0.10 depends on image ^3.2.2 and flutter_launcher_icons 0.12.0 depends on image ^4.0.15, flutter_pos_printer_platform >=1.0.10 is incompatible with flutter_launcher_icons 0.12.0.`

Can this package dependency be upgraded to image 4.x?

Joby

**Comment by waqadArshad** [comment]
@jobypthomas Yes, just make a fork and update the dependency and use that fork in your project.

**Comment by arthas1888** [comment]
@jobypthomas and @waqadArshad  please upgrade the dependency to v1.2.0 it supports image 4.x.x
