### ISSUE TITLE
Byte length restriction on printerManager.send

### ISSUE THREAD

**Issue by jobypthomas** [arthas1888/flutter_pos_printer_platform#31]
Hi,
I am trying out this plugin for bluetooth printing. For a long print it only prints initial part of it. Do we have any restriction on size of the bytes that can be send to printerManager.send()?
I am using Android and bluetooth.
@arthas1888  
@xaldarof

**Comment by jobypthomas** [comment]
Based on the trial and error it looks like a 200 chars limit.

**Comment by jobypthomas** [comment]
Update: When I batch it up with 200 bytes it worked.

**Comment by jobypthomas** [comment]
Does anyone have this issue?

**Comment by arthas1888** [comment]
do you have some code to reproduce it?, please comment your issue completely....

**Comment by jobypthomas** [comment]
@arthas1888 
`
import 'dart:io';
import 'package:esc_pos_utils/esc_pos_utils.dart';
import 'package:flutter_pos_printer_platform/flutter_pos_printer_platform.dart';
import 'package:hooks_riverpod/hooks_riverpod.dart';
import 'package:intl/intl.dart';

final invoicesPrintServiceTestProvider =
    Provider<InvoicesPrintServiceTest>((ref) {
  final service = InvoicesPrintServiceTest();
  return service;
});

class InvoicesPrintServiceTest {
  InvoicesPrintServiceTest();

  Future<List<int>> generateBytesForPrinting(
    Generator generator,
  ) async {
    List<int> bytes = [];
    List<Map> items = [];
    final now = DateTime.now();
    final formatter = DateFormat('MM/dd/yyyy hh:mm a');
    final String timestamp = formatter.format(now);
    List<InvItem> invoiceItems = [];
    invoiceItems.add(InvItem(itemName: 'Item1', quantity: 1));
    invoiceItems.add(InvItem(itemName: 'Item2', quantity: 2));
    invoiceItems.add(InvItem(itemName: 'Item3', quantity: 3));
    invoiceItems.add(InvItem(itemName: 'Item4', quantity: 4));
    invoiceItems.add(InvItem(itemName: 'Item5', quantity: 5));
    invoiceItems.add(InvItem(itemName: 'Item6', quantity: 6));
    invoiceItems.add(InvItem(itemName: 'Item7', quantity: 7));
    invoiceItems.add(InvItem(itemName: 'Item8', quantity: 8));
    invoiceItems.add(InvItem(itemName: 'Item9', quantity: 9));
    invoiceItems.add(InvItem(itemName: 'Item10', quantity: 10));
    invoiceItems.forEach((element) {
      var map = new Map();
      map['item'] = element.itemName;
      map['quantity'] = element.quantity;
      items.add(map);
    });
    bytes += generator.text(
      'My Test Business',
      styles: const PosStyles(
        align: PosAlign.center,
        height: PosTextSize.size2,
        width: PosTextSize.size2,
        bold: true,
      ),
    );
    bytes += generator.emptyLines(1);
    bytes += generator.text(
      'Event Date: ${DateFormat.yMMMd().format(DateTime.now())}',
      styles: const PosStyles(
        align: PosAlign.center,
        height: PosTextSize.size1,
        width: PosTextSize.size1,
        bold: true,
      ),
    );
    bytes += generator.emptyLines(1);
    bytes += generator.text(
      'Invoice # 12345',
      styles: const PosStyles(
        align: PosAlign.center,
        height: PosTextSize.size2,
        width: PosTextSize.size2,
        bold: true,
      ),
    );
    // bytes += generator.hr();

    bytes += generator.feed(1);
    bytes += generator.row(
      [
        PosColumn(
          text: '#'.padRight(5, ' '),
          width: 1,
          styles: PosStyles(
            align: PosAlign.left,
            underline: true,
            height: PosTextSize.size1,
            width: PosTextSize.size1,
            bold: true,
          ),
        ),
        PosColumn(
          text: 'Item'.padRight(30, ' '),
          width: 8,
          styles: PosStyles(
            align: PosAlign.left,
            underline: true,
            height: PosTextSize.size1,
            width: PosTextSize.size1,
            bold: true,
          ),
        ),
        PosColumn(
          text: 'Count'.padLeft(6, ' '),
          width: 2,
          styles: PosStyles(
            align: PosAlign.right,
            underline: true,
            height: PosTextSize.size1,
            width: PosTextSize.size1,
            bold: true,
          ),
        ),
        PosColumn(
          text: ' '.padRight(4, ' '),
          width: 1,
          styles: PosStyles(align: PosAlign.right),
        ),
      ],
    );
    bytes += generator.emptyLines(1);
    bytes += generator.feed(1);
    int count = 0;
    for (Map item in items) {
      count++;
      bytes += generator.row(
        [
          PosColumn(
            text: '$count'.padRight(30, ' '),
            width: 1,
            styles: PosStyles(
              height: PosTextSize.size1,
              width: PosTextSize.size1,
              // bold: true,
            ),
          ),
          PosColumn(
            text: '${item['item']}'.padRight(30, ' '),
            width: 8,
            styles: PosStyles(
              height: PosTextSize.size1,
              width: PosTextSize.size1,
              // bold: true,
            ),
          ),
          PosColumn(
            text: '${item['quantity']}'.toString().padLeft(6, ' '),
            width: 2,
            styles: PosStyles(
              align: PosAlign.right,
              height: PosTextSize.size1,
              width: PosTextSize.size1,
              // bold: true,
            ),
          ),
          PosColumn(
            text: ' '.padRight(4, ' '),
            width: 1,
            styles: PosStyles(align: PosAlign.right),
          ),
        ],
      );
      // bytes += generator.emptyLines(1);
      bytes += generator.feed(1);
    }
    bytes += generator.feed(1);
    bytes += generator.text('Total Count: ${invoiceItems.length}');
    bytes += generator.feed(1);
    bytes += generator.text('Order Taken By: Some User');
    bytes += generator.text('Phone#: 111-111-1111');
    bytes += generator.feed(1);
    bytes += generator.text(
      timestamp,
      styles: PosStyles(
        align: PosAlign.center,
        height: PosTextSize.size1,
        width: PosTextSize.size1,
      ),
      linesAfter: 1,
    );
    bytes += generator.feed(2);
    bytes += generator.cut();
    bytes += generator.feed(2);

    print('Print Size: ${bytes.length}');
    return bytes;
  }

  Future<void> printEscPosTest(
    PrinterManager printerManager,
    BluetoothPrinter? bluetoothPrinter,
  ) async {
    print("**** In print ESC POS TEST ****");
    // final profile = await CapabilityProfile.load(name: 'XP-N160I');
    final profile = await CapabilityProfile.load();
    // PaperSize.mm80 or PaperSize.mm58
    final generator = Generator(PaperSize.mm80, profile);
    List<int> bytes = await generateBytesForPrinting(generator);

    List<int> chunks = [];
    int chunkSize = 150;
    bool printerConnected = false;
    if (bluetoothPrinter == null) return;
    switch (bluetoothPrinter.typePrinter) {
      case PrinterType.usb:
        bytes += generator.feed(2);
        bytes += generator.cut();
        await printerManager.connect(
            type: bluetoothPrinter.typePrinter,
            model: UsbPrinterInput(
                name: bluetoothPrinter.deviceName,
                productId: bluetoothPrinter.productId,
                vendorId: bluetoothPrinter.vendorId));
        break;
      case PrinterType.bluetooth:
        print("**** In print bluetooth");
        print(bluetoothPrinter.typePrinter);
        print(bluetoothPrinter.deviceName);
        print(bluetoothPrinter.address);
        print(bluetoothPrinter.isBle);
        print(bluetoothPrinter.deviceName);
        try {
          await printerManager.connect(
              type: bluetoothPrinter.typePrinter,
              model: BluetoothPrinterInput(
                name: bluetoothPrinter.deviceName,
                address: bluetoothPrinter.address!,
                isBle: bluetoothPrinter.isBle ?? false,
                autoConnect: true,
              ));
          printerConnected = true;
        } catch (e) {
          print(e);
        }
        await printerManager.connect(
            type: bluetoothPrinter.typePrinter,
            model: BluetoothPrinterInput(
              name: bluetoothPrinter.deviceName,
              address: bluetoothPrinter.address!,
              isBle: bluetoothPrinter.isBle ?? false,
              autoConnect: false,
            ));
        // currentStatus.value = BTStatus.connected;
        break;
      case PrinterType.network:
        bytes += generator.feed(2);
        bytes += generator.cut();
        await printerManager.connect(
            type: bluetoothPrinter.typePrinter,
            model: TcpPrinterInput(ipAddress: bluetoothPrinter.address!));
        break;
      default:
    }
    print("**** In print send:::::::::::");
    print(printerManager.currentStatusBT);
    if (printerConnected) {
      print("*** Printer Connected");
      // print(pendingTask);
      if (bluetoothPrinter.typePrinter == PrinterType.bluetooth &&
          Platform.isAndroid) {
        // TODO Status Check needs to reviewed.
        if (printerManager.currentStatusBT == BTStatus.connected) {
          print("*** Printer Status: BT Connected");
          print("*** Print Size: ${bytes.length}");
          
          // OPTION 1 : From the Sample Code...
          // It starts the sound or print job however prints nothing.
          // printerManager.send(type: bluetoothPrinter.typePrinter, bytes: bytes);

          // OPTION 2: Use chunks of 150 bytes to print in a loop
          int count = 0;
          for (var i = 0; i < bytes.length; i += chunkSize) {
            chunks = bytes.sublist(
                i, i + chunkSize > bytes.length ? bytes.length : i + chunkSize);
            count++;
            print("*** Chunk ($count): ${chunks.length}");
            await printerManager.send(
                type: bluetoothPrinter.typePrinter, bytes: chunks);
            chunks = [];
          }
        } else {
          print("*** Printer NOT Connected");
        }
      } else {
        print("*** Printer either NOT BLE or NOT Android");
        printerManager.send(type: bluetoothPrinter.typePrinter, bytes: bytes);
      }
    } else {
      print("*** Printer NOT Connected");
      print("*** Printer Reconneccting");
      await printerManager.connect(
          type: bluetoothPrinter.typePrinter,
          model: BluetoothPrinterInput(
            name: bluetoothPrinter.deviceName,
            address: bluetoothPrinter.address!,
            isBle: bluetoothPrinter.isBle ?? false,
            autoConnect: true,
          ));
    }
  }
}

class InvItem {
  String itemName;
  int quantity;
  InvItem({
    required this.itemName,
    required this.quantity,
  });
}

class BluetoothPrinter {
  int? id;
  String? deviceName;
  String? address;
  String? port;
  String? vendorId;
  String? productId;
  bool? isBle;
  bool? isConnected;

  PrinterType typePrinter;
  bool? state;

  BluetoothPrinter({
    this.deviceName,
    this.address,
    this.port,
    this.state,
    this.vendorId,
    this.productId,
    this.typePrinter = PrinterType.bluetooth,
    this.isBle = false,
    this.isConnected = false,
  });
}

`

**Comment by arthas1888** [comment]
I tested your code and everything is going well

please test with this
```dart
Future generateBytesForPrinting() async {
    List invoiceItems = [];
    List items = [];

    invoiceItems.add(InvItem(itemName: 'Item1', quantity: 1));
    invoiceItems.add(InvItem(itemName: 'Item2', quantity: 2));
    invoiceItems.add(InvItem(itemName: 'Item3', quantity: 3));
    invoiceItems.add(InvItem(itemName: 'Item4', quantity: 4));
    invoiceItems.add(InvItem(itemName: 'Item5', quantity: 5));
    invoiceItems.add(InvItem(itemName: 'Item6', quantity: 6));
    invoiceItems.add(InvItem(itemName: 'Item7', quantity: 7));
    invoiceItems.add(InvItem(itemName: 'Item8', quantity: 8));
    invoiceItems.add(InvItem(itemName: 'Item9', quantity: 9));
    invoiceItems.add(InvItem(itemName: 'Item10', quantity: 10));
    for (var element in invoiceItems) {
      var map = {};
      map['item'] = element.itemName;
      map['quantity'] = element.quantity;
      items.add(map);
    }

    List<int> bytes = [];

    // Xprinter XP-N160I
    final profile = await CapabilityProfile.load(name: 'XP-N160I');

    // PaperSize.mm80 or PaperSize.mm58
    final generator = Generator(PaperSize.mm58, profile);
    bytes += generator.setGlobalCodeTable('CP1252');

    final now = DateTime.now();
    final formatter = DateFormat('MM/dd/yyyy hh:mm a');
    final String timestamp = formatter.format(now);

    bytes += generator.text(
      'My Test Business',
      styles: const PosStyles(
        align: PosAlign.center,
        height: PosTextSize.size2,
        width: PosTextSize.size2,
        bold: true,
      ),
    );
    bytes += generator.emptyLines(1);
    bytes += generator.text(
      'Event Date: ${DateFormat.yMMMd().format(DateTime.now())}',
      styles: const PosStyles(
        align: PosAlign.center,
        height: PosTextSize.size1,
        width: PosTextSize.size1,
        bold: true,
      ),
    );
    bytes += generator.emptyLines(1);
    bytes += generator.text(
      'Invoice # 12345',
      styles: const PosStyles(
        align: PosAlign.center,
        height: PosTextSize.size2,
        width: PosTextSize.size2,
        bold: true,
      ),
    );
// bytes += generator.hr();

    bytes += generator.feed(1);
    bytes += generator.row(
      [
        PosColumn(
          text: '#'.padRight(5, ' '),
          width: 1,
          styles: const PosStyles(
            align: PosAlign.left,
            underline: true,
            height: PosTextSize.size1,
            width: PosTextSize.size1,
            bold: true,
          ),
        ),
        PosColumn(
          text: 'Item'.padRight(30, ' '),
          width: 8,
          styles: const PosStyles(
            align: PosAlign.left,
            underline: true,
            height: PosTextSize.size1,
            width: PosTextSize.size1,
            bold: true,
          ),
        ),
        PosColumn(
          text: 'Count'.padLeft(6, ' '),
          width: 2,
          styles: const PosStyles(
            align: PosAlign.right,
            underline: true,
            height: PosTextSize.size1,
            width: PosTextSize.size1,
            bold: true,
          ),
        ),
        PosColumn(
          text: ' '.padRight(4, ' '),
          width: 1,
          styles: const PosStyles(align: PosAlign.right),
        ),
      ],
    );
    bytes += generator.emptyLines(1);
    bytes += generator.feed(1);
    int count = 0;
    for (Map item in items) {
      count++;
      bytes += generator.row(
        [
          PosColumn(
            text: '$count'.padRight(30, ' '),
            width: 1,
            styles: const PosStyles(
              height: PosTextSize.size1,
              width: PosTextSize.size1,
              // bold: true,
            ),
          ),
          PosColumn(
            text: '${item['item']}'.padRight(30, ' '),
            width: 8,
            styles: const PosStyles(
              height: PosTextSize.size1,
              width: PosTextSize.size1,
              // bold: true,
            ),
          ),
          PosColumn(
            text: '${item['quantity']}'.toString().padLeft(6, ' '),
            width: 2,
            styles: const PosStyles(
              align: PosAlign.right,
              height: PosTextSize.size1,
              width: PosTextSize.size1,
              // bold: true,
            ),
          ),
          PosColumn(
            text: ' '.padRight(4, ' '),
            width: 1,
            styles: const PosStyles(align: PosAlign.right),
          ),
        ],
      );
      // bytes += generator.emptyLines(1);
      bytes += generator.feed(1);
    }
    bytes += generator.feed(1);
    bytes += generator.text('Total Count: ${invoiceItems.length}');
    bytes += generator.feed(1);
    bytes += generator.text('Order Taken By: Some User');
    bytes += generator.text('Phone#: 111-111-1111');
    bytes += generator.feed(1);
    bytes += generator.text(
      timestamp,
      styles: const PosStyles(
        align: PosAlign.center,
        height: PosTextSize.size1,
        width: PosTextSize.size1,
      ),
      linesAfter: 1,
    );
    bytes += generator.feed(2);
    // bytes += generator.cut();
    // bytes += generator.feed(2);

    print('Print Size: ${bytes.length}');
    _printEscPos(bytes, generator);
  }
  
   /// print ticket
  void _printEscPos(List<int> bytes, Generator generator) async {
    if (selectedPrinter == null) return;
    var bluetoothPrinter = selectedPrinter!;

    switch (bluetoothPrinter.typePrinter) {
      case PrinterType.usb:
        bytes += generator.feed(2);
        bytes += generator.cut();
        await printerManager.connect(
            type: bluetoothPrinter.typePrinter,
            model: UsbPrinterInput(name: bluetoothPrinter.deviceName, productId: bluetoothPrinter.productId, vendorId: bluetoothPrinter.vendorId));
        pendingTask = null;
        break;
      case PrinterType.bluetooth:
        bytes += generator.cut();
        await printerManager.connect(
            type: bluetoothPrinter.typePrinter,
            model: BluetoothPrinterInput(
                name: bluetoothPrinter.deviceName,
                address: bluetoothPrinter.address!,
                isBle: bluetoothPrinter.isBle ?? false,
                autoConnect: _reconnect));
        pendingTask = null;
        if (Platform.isAndroid) pendingTask = bytes;
        break;
      case PrinterType.network:
        bytes += generator.feed(2);
        bytes += generator.cut();
        await printerManager.connect(type: bluetoothPrinter.typePrinter, model: TcpPrinterInput(ipAddress: bluetoothPrinter.address!));
        break;
      default:
    }
    if (bluetoothPrinter.typePrinter == PrinterType.bluetooth && Platform.isAndroid) {
      if (_currentStatus == BTStatus.connected) {
        printerManager.send(type: bluetoothPrinter.typePrinter, bytes: bytes);
        pendingTask = null;
      }
    } else {
      printerManager.send(type: bluetoothPrinter.typePrinter, bytes: bytes);
    }
  }
```

as you can see the receipt was printed pretty good

![WhatsApp Image 2023-04-18 at 9 37 58 AM](https://user-images.githubusercontent.com/5170748/232811863-bc8c0682-7951-416b-8b9d-b0565fd7761f.jpeg)

**Comment by jobypthomas** [comment]
@arthas1888 Thank you! Do you know if it is available in Amazon.com or would you please advise where do I buy it from?

**Comment by arthas1888** [comment]
you can get it in aliexpress
