### ISSUE TITLE
PosColumn PosAlign.right contains Japanese or Chinese,break line not correct

### ISSUE THREAD

**Issue by rrchx** [arthas1888/flutter_pos_printer_platform#32]
Please print like this！
row([
PosColumn(width:8, text: '豚肉・木耳と玉子炒め弁当', styles: PosStyles(align: PosAlign.left), containsChinese: true),
PosColumn(width:4, text: '￥1,990', styles: PosStyles(align: PosAlign.right), containsChinese: true),
])

'￥1,990' will be 2 lines for print！

**Comment by arthas1888** [comment]
hi @rrchx  now it is possible

```
    import 'package:flutter_pos_printer_platform/esc_pos_utils_platform/esc_pos_utils_platform.dart';
    ...
    // Chinese characters
    bytes += generator.row([
      PosColumn(width: 8, text: '豚肉・木耳と玉子炒め弁当', styles: const PosStyles(align: PosAlign.left), containsChinese: true),
      PosColumn(width: 4, text: '￥1,990', styles: const PosStyles(align: PosAlign.right), containsChinese: true),
    ]);

```

please look at the example https://pub.dev/packages/flutter_pos_printer_platform/example
and transfer money to my paypal

**Comment by arthas1888** [comment]
you can send money using wester union is the easy way
