### ISSUE TITLE
It looks like the status never seen to be altered.

### ISSUE THREAD

**Issue by jeffersonjpr** [arthas1888/flutter_pos_printer_platform#4]
When I run the example, the function responsible to alter the `_currentUsbStatus = status` never get called.
![image](https://user-images.githubusercontent.com/22519020/186665888-26a89a09-3a81-463a-a93f-2c1ceea69e7f.png)
*I've just added some comments and prints*

If I skip the status check, the job is sent to the printer normally:
![image](https://user-images.githubusercontent.com/22519020/186666831-e35a7182-3fac-479d-b08c-d605ce034fdf.png)
*Again, just some comments and prints*

Am I doing something wrong? 

I'm on windows. Running the app on windows.

**Comment by arthas1888** [comment]
Hi, you are wrong, as you can see the currentUsbStatus only works with Android, 
over Windows for now is not possible to check the connection status
