### ISSUE TITLE
Printing arabic character

### ISSUE THREAD

**Issue by SidouAbr** [arthas1888/flutter_pos_printer_platform#41]
i got this error when trying to print an arabic string,
    bytes += generator.text('السلام عليكم');
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument (string): Contains invalid characters.: "السلام عليكم".

I tried this, 
 String arabicText = 'السلام عليكم';
List<int> byteArabString = utf8.encode(arabicText);
    bytes += generator.rawBytes(byteArabString);
    
    its print incorrect symbole

**Comment by mohammadhprp** [comment]
Is there any solution to this problem?

**Comment by seragsabrysakr** [comment]
did you find solution

**Comment by seragsabrysakr** [comment]
@SidouAbr

**Comment by marwenbk** [comment]
What a shame, tens of Arabian developers and we're unable to add the required customizations for Arabic letter's profile or use utf-8

**Comment by seragsabrysakr** [comment]
we waiting for you to do that

**Comment by SidouAbr** [comment]
> did you find solution
> 

Not yet, i have go to print it as pdf or png...

**Comment by seragsabrysakr** [comment]
how you did it can you help me
