### ISSUE TITLE
How to connect with cash drawer

### ISSUE THREAD

**Issue by thihas0ehtet** [arthas1888/flutter_pos_printer_platform#42]

**Comment by colinxiaoyu** [comment]
you may add this code  ：
_sendBytesToPrint(List<int> bytes, PrinterType type) async { 
      PrinterManager.instance.send(type: type, bytes: bytes);
    }

android code is ：
this.printerConnection.write(new byte[]{0x1B, 0x70, 0x00, 0x3C, (byte) 0xFF});
        this.printerConnection.send(100);

**Comment by colinxiaoyu** [comment]
you may use pulseDrawer  in EscPosPrinter

**Comment by arthas1888** [comment]
you must to send the following bytes
bytes += [0x1b, 0x70, 0x00, 0x1e, 0xff, 0x00];
that's all
