### ISSUE TITLE
type 'Null' is not a subtype of type 'String'

### ISSUE THREAD

**Issue by smursalov** [arthas1888/flutter_pos_printer_platform#45]
I receive this error while trying to discover my USB-connected printer.

```
type 'Null' is not a subtype of type 'String'
#0      UsbPrinterConnector.discovery (package:flutter_pos_printer_platform/src/connectors/usb.dart:127)
<asynchronous suspension>
```

Seems like my printer does not have the `product` information, and thus leads to an error, please consider this edge-case.

**Comment by smursalov** [comment]
Same issue: https://github.com/arthas1888/flutter_pos_printer_platform/issues/37

**Comment by arthas1888** [comment]
Solved in the last release

**Comment by smursalov** [comment]
@arthas1888 can you link to the relevant commit? I don't see the fix.

**Comment by arthas1888** [comment]
commit cc5a09b812070442a35ee73e0d7c5b615bef1dea
