### ISSUE TITLE
Columns content are pushed to the right if some left columns have Thai character

### ISSUE THREAD

**Issue by Johnny-Luu** [arthas1888/flutter_pos_printer_platform#48]
Hi everyone. I'm trying to print the report that have Thai character, so i used the textEncoded() method like this to render table rows:
![image](https://github.com/arthas1888/flutter_pos_printer_platform/assets/67548757/6dc1613c-58a3-4f06-bfa8-7a16527b5776)

And here is the getThaiEncoded() method:

`
Future<Uint8List> getThaiEncoded(String text) async =>
    await CharsetConverter.encode(
      'Windows-874',
      text,
    );
`

And this is the result:
![Screenshot 2023-06-22 231048](https://github.com/arthas1888/flutter_pos_printer_platform/assets/67548757/28a022b8-6bc1-43bd-876b-41899c1011b2)

All the rows that have 2nd column contains only Latin character (like the one i've highlighted) is perfectly aligned, but the others which have Thai, right columns take some extra spaces and pushed back to the right even though they're from the same source code. What's going on with the textEncoded() method?
Any help will be appreciated please

**Comment by arthas1888** [comment]
this is not problem of this lib, also ya con rewrite that part
