### ISSUE TITLE
MissingPluginException

### ISSUE THREAD

**Issue by nikolajocic** [arthas1888/flutter_pos_printer_platform#5]
Hi.

I tried to test Your plugin (Windows app), but got error when start demo (for list of USB printers):

Unhandled Exception: MissingPluginException(No implementation found for method getList on channel com.sersoluciones.flutter_pos_printer_platform)

Can You, please, help with this error?

**Comment by arthas1888** [comment]
solved!
update to flutter_pos_printer_platform: ^1.0.4
