### ISSUE TITLE
Exception has occurred. RangeError (RangeError: Invalid value: Not in inclusive range 0..9826: 9876)

### ISSUE THREAD

**Issue by toulaoBD** [arthas1888/flutter_pos_printer_platform#50]
bytes += generator.imageRaster(decodeImage(imageBytes)!, align: PosAlign.center);

**Comment by LeiYao123** [comment]
I also have a similar problem. When the image is large, this step will take a lot of time, about 10 seconds

**Comment by arthas1888** [comment]
this is not problem of this lib, you are not extract the bytes correctly from image

**Comment by assem16399** [comment]
I have the same issue And I am using the code of printing Image that is provided in example.dart file of the package
I'm just changing the image file itself that I want to print and it is not printing while the provided image file with the package example is printing with no issues.
How can changing only the printed image gives me this error?

**Comment by assem16399** [comment]
@toulaoBD Did you find any solution?
