### ISSUE TITLE
Exception: model must be type of TcpPrinterInput  when try to connect in ios 

### ISSUE THREAD

**Issue by seragsabrysakr** [arthas1888/flutter_pos_printer_platform#53]
@arthas1888

**Comment by seragsabrysakr** [comment]
![Screenshot 2023-06-29 at 5 25 26 PM](https://github.com/arthas1888/flutter_pos_printer_platform/assets/81074317/10f20402-d4a6-473b-974e-1870f5da0435)

**Comment by arthas1888** [comment]
you have to put this, see the example
```dart
// Register DartPingIOS
  if (Platform.isIOS) {
    DartPingIOS.register();
  }
```
