### ISSUE TITLE
USB Printer freezes after printing mutiple (10-12) tickets with a qr code on it

### ISSUE THREAD

**Issue by markbreuss** [arthas1888/flutter_pos_printer_platform#56]
This is a pretty strange behavior but after printing 10 to 12 receipts that include a qr code, the pritner stops printing until I turn the printer on and off again.

I have worked around it by printing the qr code as an image but stil this might be a bug stumble over as well.

I could reproduce this only on usb devices.

**Comment by arthas1888** [comment]
hi, each printer works a little bit different in my case it does not happen, I think is problem of your printer, if you guess this is a bug I need the exception to be thrown.

**Comment by markbreuss** [comment]
Hi @arthas1888,

thanks for your response! Thats the strange thing it seems like no exception is beeing thrown at all.
And fure sure it is somthing about the printer (its a new Epson TM M30)

If I have time I'll investigate and see if I can find something.
