### ISSUE TITLE
Printing Image Issue

### ISSUE THREAD

**Issue by assem16399** [arthas1888/flutter_pos_printer_platform#58]
When I try to print an image using the same image in the package example.dart file, it prints successfully, however when I try to print another Image it gives me this error:

E/flutter (11695): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: RangeError: Invalid value: Not in inclusive range 0..12478: 12668
E/flutter (11695): #0      List.insertAll (dart:core-patch/growable_array.dart:44:7)
E/flutter (11695): #1      Generator._toRasterFormat (package:flutter_pos_printer_platform/esc_pos_utils_platform/src/generator.dart:180:25)
E/flutter (11695): #2      Generator.imageRaster (package:flutter_pos_printer_platform/esc_pos_utils_platform/src/generator.dart:740:38)
E/flutter (11695): #3      _MyAppState._printReceiveTest (package:final_printer_test_2/main.dart:261:26)
E/flutter (11695): <asynchronous suspension>
E/flutter (11695): 

My Code:
final ByteData data = await rootBundle.load('assets/z.png');
    if (data.lengthInBytes > 0) {
      final Uint8List imageBytes = data.buffer.asUint8List();
      // decode the bytes into an image
      final decodedImage = img.decodeImage(imageBytes)!;
      // Create a black bottom layer
      // Resize the image to a 130x? thumbnail (maintaining the aspect ratio).
      img.Image thumbnail = img.copyResize(decodedImage, height: 130);
      // creates a copy of the original image with set dimensions
      img.Image originalImg =
          img.copyResize(decodedImage, width: 380, height: 130);
      // fills the original image with a white background
      img.fill(originalImg, color: img.ColorRgb8(255, 255, 255));
      var padding = (originalImg.width - thumbnail.width) / 2;

      //insert the image inside the frame and center it
      drawImage(originalImg, thumbnail, dstX: padding.toInt());

      // convert image to grayscale
      var grayscaleImage = img.grayscale(
        originalImg,
      );

      bytes += generator.feed(1);
      // bytes += generator.imageRaster(img.decodeImage(imageBytes)!, align: PosAlign.center);
      bytes += generator.imageRaster(grayscaleImage, align: PosAlign.center);
      bytes += generator.feed(1);
    }

**Comment by arthas1888** [comment]
you are not decode quite good your image

**Comment by assem16399** [comment]
Thanks for replay.
Could you please tell me how to decode it in good way?
and how I can achieve this dynamically as the printed image should be dynamic depending on the user?
