### ISSUE TITLE
in version 1.4.1 (latest one) I got this issue and esc_pos_printer 4.1.0 is the lasted version of that package

### ISSUE THREAD

**Issue by eslamesmail-hub** [arthas1888/flutter_pos_printer_platform#61]
![Screenshot 2023-07-14 000057](https://github.com/arthas1888/flutter_pos_printer_platform/assets/70852067/6824bd58-768e-4312-8007-14ae5c7896b6)

**Comment by eslamesmail-hub** [comment]
when I lower down the page to version 1.1.0 it works fine but in android and windows and not working in ios

**Comment by arthas1888** [comment]
version 1.4.1 you cannot use the lib esc pos printer

**Comment by eslamesmail-hub** [comment]
I know, is there any way we can fix this?!

**Comment by arthas1888** [comment]
please see the example of this lib
